### ISSUE TITLE
ADD_ACCESSSPEC, didn't find it

### ISSUE THREAD

**Issue by ghiewa** [dockletinc/llrp#1]
Cann't find ADD_ACCESSSPEC in request.go, haven't implement?

**Comment by ghiewa** [comment]
Dear,

Possible to write you mail? Please advise 
:)

**Comment by pictca** [comment]
Hi. I editor and currently I work on rust project with new team.
I move project to  https://github.com/pictca/llrp.
~3 day I will fix your issue.
Pichit - Pichit@incsprint.com

**Comment by dockletinc** [comment]
move to https://github.com/pictca/llrp.
close #1
